version: "3.8"
services:
  es01:
    image: elasticsearch:7.10.1
    ports:
      - 9201:9200
      - 9301:9300
    environment:
      node.name: es01
      discovery.seed_hosts: es01,es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      cluster.name: mycluster
      ES_JAVA_OPTS: -Xms256m -Xmx256m

  es02:
    image: elasticsearch:7.10.1
    ports:
      - 9202:9200
      - 9302:9300
    environment:
      node.name: es02
      discovery.seed_hosts: es01,es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      cluster.name: mycluster
      ES_JAVA_OPTS: -Xms256m -Xmx256m

  es03:
    image: elasticsearch:7.10.1
    ports:
      - 9203:9200
      - 9303:9300
    environment:
      node.name: es03
      discovery.seed_hosts: es01,es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      cluster.name: mycluster
      ES_JAVA_OPTS: -Xms256m -Xmx256m

  kibana:
    image: kibana:7.10.1
    ports:
      - 5601:5601
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://es01:9200","http://es02:9200","http://es03:9200"]'
