version: "3.8"
services:
  es01:
    image: elasticsearch:7.10.1
    ports:
      - 9201:9200
      - 9301:9300
    environment:
      discovery.seed_hosts: es01
      ES_JAVA_OPTS: -Xms256m -Xmx256m # min and max Java heap size
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:9200" ]
      interval: 10s
      timeout: 10s
      retries: 120
    volumes:
      - .es-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.10.1
    ports:
      - 5601:5601
    depends_on:
      es01:
        condition: service_healthy
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://es01:9200"]'
